In [3]:
#Arbol de Desicion en Python

#Codigo extraido del siguiente tutorial:
#    https://www.youtube.com/watch?v=tNa99PG8hR8

#Utilizaremos el clasico dataset de Iris

#set de datos
from sklearn.datasets import load_iris
iris=load_iris()
print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])
for i in range(len(iris.target)):
    print("Ejemplo %d: label %s, features %s" % (i,iris.target[i],iris.data[i]))

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0
Ejemplo 0: label 0, features [5.1 3.5 1.4 0.2]
Ejemplo 1: label 0, features [4.9 3.  1.4 0.2]
Ejemplo 2: label 0, features [4.7 3.2 1.3 0.2]
Ejemplo 3: label 0, features [4.6 3.1 1.5 0.2]
Ejemplo 4: label 0, features [5.  3.6 1.4 0.2]
Ejemplo 5: label 0, features [5.4 3.9 1.7 0.4]
Ejemplo 6: label 0, features [4.6 3.4 1.4 0.3]
Ejemplo 7: label 0, features [5.  3.4 1.5 0.2]
Ejemplo 8: label 0, features [4.4 2.9 1.4 0.2]
Ejemplo 9: label 0, features [4.9 3.1 1.5 0.1]
Ejemplo 10: label 0, features [5.4 3.7 1.5 0.2]
Ejemplo 11: label 0, features [4.8 3.4 1.6 0.2]
Ejemplo 12: label 0, features [4.8 3.  1.4 0.1]
Ejemplo 13: label 0, features [4.3 3.  1.1 0.1]
Ejemplo 14: label 0, features [5.8 4.  1.2 0.2]
Ejemplo 15: label 0, features [5.7 4.4 1.5 0.4]
Ejemplo 16: label 0, features [5.4 3.9 1.3 0.4]
Ejemplo 17: label 0, features [5.1 3.5 1.4 0.3]
Ejemplo

In [7]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
test_idx=[0,50,100]

#Set de entrenamiento
train_target = np.delete(iris.target,test_idx)
train_data = np.delete(iris.data,test_idx,axis = 0)

#Set de prueba
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

arbol = DecisionTreeClassifier()
arbol.fit(train_data,train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [8]:
print(test_target)
print(arbol.predict(test_data))

[0 1 2]
[0 1 2]


In [10]:
#Visualicemos el arbol de desicion

from sklearn.externals.six import StringIO
import pydot
dot_data=StringIO()
tree.export_graphviz(arbol,
                     out_file=dot_data,
                     feature_names=iris.feature_names,
                     class_names=iris.target_names,
                     filled=True,
                     rounded=True,
                     impurity=False)
graph=pydot.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")

ModuleNotFoundError: No module named 'pydot'

In [13]:
print(test_data[0],test_target[0])
print(iris.feature_names,iris.target_names)

[5.1 3.5 1.4 0.2] 0
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']


In [14]:
print(test_data[1],test_target[1])
print(iris.feature_names,iris.target_names)

[7.  3.2 4.7 1.4] 1
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
