Código para el método de los K-vecinos cercanos

In [ ]:
#numpy contiene operaciones para arreglos
#sklearn contiene algoritmos de machine learning 
#sklearn tambien contiene datasets de prueba como el famoso set iris
#train_test_split sirve para dividir la data entre set de entrenamiento
# y set de testing
import numpy as np
import sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [5]:
#Cargamos nuestro set de datos en una varible
#tipo de dato Bunch (parecido a un diccionario)

iris=load_iris()

In [7]:
#llaves del set de datos
iris.keys()

['target_names', 'data', 'target', 'DESCR', 'feature_names']

In [8]:
#dentro de data contiene una matriz de las mediciónes de las flores
iris["data"]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
#Nombres de las clasificaciones
iris["target_names"]

array(['setosa', 'versicolor', 'virginica'], dtype='|S10')

In [10]:
#Clasificación en numérico
#Importante: El target siempre debe ser numérico

iris["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
#Contiene el nombre de cada columna de la data

iris["feature_names"]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
#Se separa la data entre el set de entrenamiento
#y el set de testing

X_train,X_test,y_train,y_test= train_test_split(iris["data"],iris["target"])

In [14]:
#Retorna el tamaño de nuestro arreglo que servirá para entrenar
X_train.shape

(112L, 4L)

In [27]:
#Target de entrenamiento
y_train.shape

(112L,)

In [28]:
#set de testing
X_test.shape

(38L, 4L)

In [29]:
#Target de testing
y_test.shape

(38L,)

In [30]:
#importamos nuestro algoritmo clasificador
#Método de k-vecinos cercanos (k-nearest neighbors, abreviado knn)
#una introducción a este método https://es.wikipedia.org/wiki/K_vecinos_m%C3%A1s_pr%C3%B3ximos
#A grandes razgos éste método compara las características del 
#nuevo dato a clasificar con "k" puntos más cercanos a él, 
#y lo clasifica dependiendo la clasificación de sus "vecinos cercanos"
from sklearn.neighbors import KNeighborsClassifier

In [32]:
#Tomamos 7 vecinos cercanos

knn=KNeighborsClassifier(n_neighbors=7)

In [33]:
#fit entrena al modelo, con la data anteriormente creada
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=7, p=2,
           weights='uniform')

In [34]:
#score evalua que tan bien aprendió el algoritmo
knn.score(X_test,y_test)

0.9736842105263158

In [35]:
#prueba para pronosticar a que target pertenece un punto dado
knn.predict([[1.2,3.4,5.6,1.1]])

array([1])

In [36]:
iris.target_names
#Con base en el resultado previo podemos decir que los valores pertenecen a el 
#target "versicolor"


array(['setosa', 'versicolor', 'virginica'], dtype='|S10')