In [1]:
#Librería que contiene las funciones necesarias
import numpy as np

In [2]:
#Función Sigmoide f(x)=1/(1+Exp[-x])

def nonlin(x,deriv=False):
    if (deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))


In [12]:
#iniciando nuestro dataset 
#donde cada fila es un ejemplo de entrenamiento
#y cada columna representa una neurona


# en este ejemplo se tienen 4 ejemplos 
#de entrenamiento con 3 neuronas cada uno

#input data
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array([ [0],
               [1],
               [1],
               [0]])

print X 
print y

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [10]:
#se generan números aleatorios con 
#la misma semilla para fines de 
#que la depuracion sea mas facil

np.random.seed(1)

In [9]:

#se crea la sinapsis
#al tener 3 capas en nuestra red necesitamos 2 matrices 
#de sinapsis con pesos asignados aleatoriamente

#synapses
syn0=2*np.random.random((3,4))-1
syn1=2*np.random.random((4,1))-1

print syn0
print syn1

[[-0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523]
 [ 0.7527783   0.78921333 -0.82991158 -0.92189043]]
[[-0.66033916]
 [ 0.75628501]
 [-0.80330633]
 [-0.15778475]]


In [7]:

#código de entrenamiento
#el ciclo for recorrerá el código para optimizar 
#la red para el dataset dado


#la primer capa es solo para insertar información

#el paso de prediccion efecuará la multiplicación
#de matrices entre capa y sinapsis

#luego se usa el sigmoide en todos los valores
#para crear la siguiente capa
#y se repite el proceso para conseguir la próxima capa
#mejorando la predicción

#y se compara con la salida esperada
#restando para extraer el ratio de error
   
#train step
for j in xrange(100000):
    
    l0=X
    l1=nonlin(np.dot(l0,syn0))
    l2=nonlin(np.dot(l1,syn1))
    
    l2_error=y-l2
    
    if(j%10000)==0:
        print "Error: " + str(np.mean(np.abs(l2_error))) #para ver como se comporta el error
        
    #Comienza el Backpropagation
    l2_delta= l2_error*nonlin(l2,deriv=True)
    
    l1_error=l2_delta.dot(syn1.T)
    
    l1_delta=l1_error*nonlin(l1,deriv=True)
    
    #Actualiza los pesos de  forma aleatoria
    #update weights
    syn1 +=l1.T.dot(l2_delta)
    syn0+=l0.T.dot(l1_delta)

Error: 0.49641003190272537
Error: 0.008584525653247153
Error: 0.0057894598625078085
Error: 0.004629176776769985
Error: 0.003958765280273649
Error: 0.003510122567861679
Error: 0.0031835023858748273
Error: 0.0029323063422830725
Error: 0.0027315064182105073
Error: 0.0025663172400400254


In [8]:
print "\nSalida después del entrenamiento:"
print l2


Salida después del entrenamiento:
[[0.00199094]
 [0.99751458]
 [0.99771098]
 [0.00294418]]
